plugin: community.proxmox.proxmox

url: https://192.168.1.5:8006
user: terraform@pve
node: proxmox
token_id: provider
token_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33636164316663633935303866323963653531366364373333396365313162666266323238623334
          3662346166303236326536643862323532376232393837380a613263633532363665386432613637
          36383635373237376431646436663662316631393938633764393338386661613234303730636562
          6437396538303939630a643636323334636664323737383565663962653234303637363030373136
          37643766366130633130306232343063333763383736343231626437373566353936306238646138
          3765396139663239666239623362666232666532383432333136

validate_certs: false
want_facts: true
qemu_extended_statuses: true

keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""

compose:
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
