apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - namespace.yml
  - pvc-config.yml
  - pvc-media.yml
  - pv-media.yml
  - deployment.yml
  - service.yml
  - ingress.yml
