apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-movies
spec:
  storageClassName: "nfs-media"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.39
    path: /volume1/HomeLab-NFS/media/movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-shows
spec:
  storageClassName: "nfs-media"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.39
    path: /volume1/HomeLab-NFS/media/shows
