apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-movies
spec:
  storageClassName: "nfs-media"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-jellyfin-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-shows
spec:
  storageClassName: "nfs-media"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-jellyfin-shows
