apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netbird

helmCharts:
  - name: netbird
    repo: https://netbirdio.github.io/helms
    version: 1.9.0
    releaseName: netbird
    namespace: netbird
    valuesFile: values.yml

patches:
  - path: patch-netbird-dashboard-vault.yml
    target:
      kind: Deployment
      name: netbird-dashboard
      namespace: netbird
  - path: patch-netbird-relay-vault.yml
    target:
      kind: Deployment
      name: netbird-relay
      namespace: netbird
  - path: patch-netbird-management-vault.yml
    target:
      kind: Deployment
      name: netbird-management
      namespace: netbird
