apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-management
  namespace: netbird
spec:
  template:
    spec:
      containers:
        - name: netbird-management
          command: ["/usr/bin/sh", "-c"]
          args:
            - |
              . /vault/secrets/secrets.env
              exec /go/bin/netbird-mgmt management
