- name: Restart clamav-daemon
  ansible.builtin.service:
    name: clamav-daemon
    state: restarted

- name: Restart clamav-freshclam
  ansible.builtin.service:
    name: clamav-freshclam
    state: restarted
