collections:
  - name: community.general
    version: "11.4.0"
  - name: kubernetes.core
    version: "3.2.0"
  - name: community.proxmox
    version: "1.3.0"
  - name: community.kubernetes
    version: "2.0.1"
