apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  vaultAuthRef: authentik
  mount: infra
  type: kv-v2
  path: k8s/authentik/secrets
  refreshAfter: 1h
  destination:
    create: true
    overwrite: true
    name: authentik-postgres-credentials
    type: Opaque
